# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-repo',
                'doc_host': 'https://ptipri047.github.io',
                'git_url': 'https://github.com/ptipri047/nbdev-repo',
                'lib_path': 'nbdev_repo'},
  'syms': {'nbdev_repo.core': {'nbdev_repo.core.foo': ('core.html#foo', 'nbdev_repo/core.py')}}}
