# Autogenerated by nbdev

d = { 'settings': { 'branch': '{branch}',
                'doc_baseurl': '/{lib_name}/',
                'doc_host': 'https://{user}.github.io',
                'git_url': 'https://github.com/{user}/{repo}/',
                'lib_path': '{lib_name}'},
  'syms': { '{lib_name}.core': { '{lib_name}.core.foo': ('core.html#foo', '{lib_name}/core.py'),
                                 '{lib_name}.core.tof': ('core.html#tof', '{lib_name}/core.py')}}}
